name: Caddy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Check Go version
        run: go version

      - name: Install xcaddy from source
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          xcaddy version

      - name: Build caddy from source
        run: |
          xcaddy build $(sed 's/^/--with /' caddy/plugins | xargs)
          ./caddy version
          echo "CADDY_VERSION=$(./caddy version | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: caddy_${{ env.CADDY_VERSION }}
          path: caddy
